### ISSUE TITLE
RemindLogin message error

### ISSUE THREAD

**Issue by JoRa22** [PEMapModder/HereAuth#51]
Hi,

I am trying to edit the format of RemindLogin message for both Register & Login. It will display fine until i try to format color with "§a". If I add the "§a" before the text and change nothing else, the message becomes a popup and remains white. How can I successfully broadcast theis message in color and possibly add a bold "»" a the start? Thank you and sorry for any format issue, This is my first post here.

This is line 90 in config.yml

``` yaml
RemindLogin:
  # Messages to send to players
  Message:
    Register: 'Please register by typing a password directly into chat'
    Login: 'Please login by typing your password directly into chat'
  # Type of message.
  # Options: chat, popup, tip, none
  Type: chat
  # Frequency interval, in seconds, of how often to send the message
  # Value is rounded down to 0.05 second
  Interval: 2
```
