### ISSUE TITLE
How to dissable no of acc per player

### ISSUE THREAD

**Issue by Ishannaik** [PEMapModder/HereAuth#64]
How to dissable no of acc per player

**Comment by SOF3** [comment]
Just set it to a very large number?

**Comment by Ishannaik** [comment]
``` yaml
Registration:
  # Registration throttle. Limits number of registrations from an IP per time.
  # If ForceRegister is set to false, players who didn't register will not be counted as a registration.
  RateLimit:
    Accounts: 100000
    Days: 26500
```
